title: brumalphoto
email: your-email@example.com
description: Trap beats by @brumalsaito
baseurl: ""
url: "https://brumalphoto.github.io"
twitter_username: brumalsaito
github_username: brumalphoto
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 5
paginate_path: /posts/page:num/
permalink: /:year/:month/:day/:title/
