title: brumalphoto
description: uploading cool sounds i make
email: saitosintern@gmail.com
baseurl: ""
url: "https://brumalphoto.github.io"
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
header_pages:
  - blockchain.md
  - about.markdown
  - contact.md
  - posts.md
  - categories.md